/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
    fontFamily: {
      'sans': [
        'Arial',
        'Helvetica Neue',
        'Helvetica',
        'sans-serif',
      ],
      'serif': [
        'Times New Roman',
        'Times',
        'serif',
      ],
      'mono': [
        'Courier New',
        'Courier',
        'monospace',
      ],
      'system-ui': [
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen-Sans',
        'Ubuntu',
        'Cantarell',
        'Helvetica Neue',
        'sans-serif',
      ],
      'noto-sans': [
        'Noto Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'open-sans': [
        'Open Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'lato': [
        'Lato',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'raleway': [
        'Raleway',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'poppins': [
        'Poppins',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'montserrat': [
        'Montserrat',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'oswald': [
        'Oswald',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'roboto': [
        'Roboto',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'nunito': [
        'Nunito',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'ubuntu': [
        'Ubuntu',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'dosis': [
        'Dosis',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'quicksand': [
        'Quicksand',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'fira-sans': [
        'Fira Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'source-sans-pro': [
        'Source Sans Pro',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'karla': [
        'Karla',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'merriweather': [
        'Merriweather',
        'Georgia',
        'serif',
      ],
      'playfair-display': [
        'Playfair Display',
        'Georgia',
        'serif',
      ],
      'oswald': [
        'Oswald',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'roboto': [
        'Roboto',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'nunito': [
        'Nunito',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'ubuntu': [
        'Ubuntu',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'dosis': [
        'Dosis',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'quicksand': [
        'Quicksand',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'fira-sans': [
        'Fira Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'source-sans-pro': [
        'Source Sans Pro',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'karla': [
        'Karla',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'merriweather': [
        'Merriweather',
        'Georgia',
        'serif',
      ],
      'playfair-display': [
        'Playfair Display',
        'Georgia',
        'serif',
      ],
      'proxima-nova': [
        'Proxima Nova',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'avenir': [
        'Avenir',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'calibri': [
        'Calibri',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'futura': [
        'Futura',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'garamond': [
        'Garamond',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'georgia': [
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'helvetica': [
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'avenir-next': [
        'Avenir Next',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'baskerville': [
        'Baskerville',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'didot': [
        'Didot',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'cambria': [
        'Cambria',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'bookman': [
        'Bookman',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'trebuchet': [
        'Trebuchet MS',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'verdana': [
        'Verdana',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'impact': [
        'Impact',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'comic-sans': [
        'Comic Sans MS',
        'Comic Sans',
        'cursive',
      ],
      'arial-black': [
        'Arial Black',
        'Arial',
        'Helvetica',
        'sans-serif',
      ],
      'palatino': [
        'Palatino',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'courier': [
        'Courier',
        'Courier New',
        'monospace',
      ],
      'brandon-grotesque': [
        'Brandon Grotesque',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'futura-pt': [
        'Futura PT',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'gill-sans': [
        'Gill Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'bodoni-mt': [
        'Bodoni MT',
        'Didot',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'century-gothic': [
        'Century Gothic',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'copperplate': [
        'Copperplate',
        'Copperplate Gothic Light',
        'fantasy',
      ],
      'rockwell': [
        'Rockwell',
        'Baskerville',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'avenir-next-condensed': [
        'Avenir Next Condensed',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'bell-mt': [
        'Bell MT',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'consolas': [
        'Consolas',
        'Monaco',
        'monospace',
      ],
      'candara': [
        'Candara',
        'Calibri',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'franklin-gothic': [
        'Franklin Gothic',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'constantia': [
        'Constantia',
        'Palatino',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'corbel': [
        'Corbel',
        'Calibri',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'electronic-highway-sign': [
        'Electronic Highway Sign',
        'Dot Matrix',
        'monospace',
      ],
      'fixedsys': [
        'Fixedsys',
        'Terminal',
        'monospace',
      ],
      'mingliu': [
        'MingLiU',
        'MingLiU-ExtB',
        'PMingLiU',
        'MingLiU_HKSCS',
        'Microsoft JhengHei',
        'sans-serif',
      ],
      'impact-label': [
        'Impact Label',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'caladea': [
        'Caladea',
        'Cambria',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'tahoma': [
        'Tahoma',
        'Geneva',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'didact-gothic': [
        'Didact Gothic',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'comfortaa': [
        'Comfortaa',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'varela-round': [
        'Varela Round',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'old-standard-tt': [
        'Old Standard TT',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'museo-slab': [
        'Museo Slab',
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'petrona': [
        'Petrona',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'cutive-mono': [
        'Cutive Mono',
        'Courier New',
        'Courier',
        'monospace',
      ],
      'josefin-sans': [
        'Josefin Sans',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'lobster': [
        'Lobster',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'amarante': [
        'Amarante',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'gudea': [
        'Gudea',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'marmelad': [
        'Marmelad',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'neucha': [
        'Neucha',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'noticia-text': [
        'Noticia Text',
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'pacifico': [
        'Pacifico',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'playball': [
        'Playball',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'quattrocento': [
        'Quattrocento',
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'seaweed-script': [
        'Seaweed Script',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'stalemate': [
        'Stalemate',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'yesteryear': [
        'Yesteryear',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'vollkorn': [
        'Vollkorn',
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'vollkorn-sc': [
        'Vollkorn SC',
        'Georgia',
        'Times New Roman',
        'Times',
        'serif',
      ],
      'vt323': [
        'VT323',
        'Courier New',
        'Courier',
        'monospace',
      ],
      'yanone-kaffeesatz': [
        'Yanone Kaffeesatz',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'yeseva-one': [
        'Yeseva One',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
      'zeyada': [
        'Zeyada',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'sans-serif',
      ],
    }
  },
  plugins: [],
}